#funzione get per vedere gli utenti
GET http://localhost:3000/users/

###
#funzione get per vedere un utente
GET http://localhost:3000/users/tobia

###
#funzione get per vedere i todo
GET http://localhost:3000/users/tobia/todos




###
#aggiunge un utente
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "L",
    "password": "zawardo",
    "todos": []
}

###
#password corretta
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "tobia",
    "password": "password"
}

### 
#password errata
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "tobia",
    "password": "zawardo"
}

###
#utente errato
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "cosimo",
    "password": "password"
}

###
#utente e password errati
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "cosimo",
    "password": "zawardo"
}


###
#funzione post per aggiungere un todo
POST http://localhost:3000/users/tobia/todos
Content-Type: application/json

{
    "content" : "todo N"
}
